TRUNCATE TABLE projects;
INSERT INTO projects (id,title,slug,description,category,status,startDate,endDate,budget,funder,partners,location,beneficiaries,progress,objectives,outcomes,image,isFeatured,isActive,`order`,createdAt,updatedAt) VALUES
(1,'Tekstil Yan Sanayi Dijital Donusum Projesi','tekstil-yan-sanayi-dijital-donusum-projesi','Tekstil yan sanayi firmalarinin dijital donusumu icin kapsamli egitim ve danismanlik projesi.','national','ongoing',NULL,NULL,'2000000 TL','KOSGEB',NULL,NULL,NULL,60,NULL,NULL,NULL,1,1,1,NOW(),NOW()),
(2,'Surdurulebilir Uretim ve Dongusel Ekonomi Projesi','surdurulebilir-uretim-ve-dongusel-ekonomi-projesi','Tekstil sektorunde atik yonetimi, geri donusum ve cevre dostu uretim uygulamalarinin yayginlastirilmasi.','eu','ongoing',NULL,NULL,'500000 EUR','AB Horizon 2020',NULL,NULL,NULL,40,NULL,NULL,NULL,1,1,2,NOW(),NOW()),
(3,'KYSD Cluster Gelistirme Projesi','kysd-cluster-gelistirme-projesi','Konfeksiyon yan sanayi sektoru icin cluster yapisinin olusturulmasi ve guclendirimi projesi.','national','completed',NULL,NULL,'1500000 TL','Sanayi ve Teknoloji Bakanligi',NULL,NULL,NULL,100,NULL,NULL,NULL,0,1,3,NOW(),NOW()),
(4,'Tekstil Kimyasallari Guvenligi AR-GE Projesi','tekstil-kimyasallari-guvenligi-ar-ge-projesi','Tekstil uretiminde kullanilan kimyasallarin guvenlik testleri ve alternatif cevre dostu kimyasallarin gelistirilmesi.','rd','ongoing',NULL,NULL,'3000000 TL','TUBITAK',NULL,NULL,NULL,55,NULL,NULL,NULL,0,1,4,NOW(),NOW()),
(5,'Ihracatta Marka Olusturma ve Uluslararasilasma','ihracatta-marka-olusturma-ve-uluslararasilasma','TURQUALITY destegi ile yan sanayi firmalarinin marka kimligini olusturma ve ihracat kapasitelerini artirma projesi.','national','ongoing',NULL,NULL,'5000000 TL','Ticaret Bakanligi',NULL,NULL,NULL,35,NULL,NULL,NULL,1,1,5,NOW(),NOW()),
(6,'Tekstil Sektor Yetkinlik Merkezi Projesi','tekstil-sektor-yetkinlik-merkezi-projesi','Mesleki egitim ve sertifikasyon icin sektore ozel yetkinlik merkezi kurulumu projesi.','national','planning',NULL,NULL,'4000000 TL','MEB',NULL,NULL,NULL,20,NULL,NULL,NULL,0,1,6,NOW(),NOW()),
(7,'Akilli Tekstil ve Fonksiyonel Kumaslar AR-GE','akilli-tekstil-ve-fonksiyonel-kumaslar-ar-ge','Akilli tekstil urunlerinin gelistirilmesi ve piyasaya surulmesi projesi.','rd','ongoing',NULL,NULL,'2500000 TL','TUBITAK',NULL,NULL,NULL,65,NULL,NULL,NULL,1,1,7,NOW(),NOW()),
(8,'Tekstil Atiklari Yonetimi ve Geri Donusum','tekstil-atiklari-yonetimi-ve-geri-donusum','Tekstil atik yonetimi, geri donusum altyapisi olusturma ve dongusel ekonomi modelleri gelistirme.','national','ongoing',NULL,NULL,'1800000 TL','Cevre Bakanligi',NULL,NULL,NULL,50,NULL,NULL,NULL,0,1,8,NOW(),NOW()),
(9,'KOB Enerji Verimliligi ve Yesil Uretim','kob-enerji-verimliligi-ve-yesil-uretim','Tekstil KOB lerinde enerji verimliligi artirma ve yenilenebilir enerji kullanimi.','national','completed',NULL,NULL,'1200000 TL','KOSGEB',NULL,NULL,NULL,100,NULL,NULL,NULL,0,1,9,NOW(),NOW()),
(10,'AB Karbon Sinir Duzenlemesi Uyum Projesi','ab-karbon-sinir-duzenlemesi-uyum-projesi','CBAM kapsaminda ihracat yapan firmalarin uyum surecleri ve karbon ayak izi hesaplama.','eu','ongoing',NULL,NULL,'300000 EUR','AB LIFE',NULL,NULL,NULL,45,NULL,NULL,NULL,1,1,10,NOW(),NOW()),
(11,'Tekstil Sektor Inovasyon Merkezi','tekstil-sektor-inovasyon-merkezi','Sektor icin AR-GE ve inovasyon merkezi kurulumu, universite-sanayi isbirligi projesi.','rd','ongoing',NULL,NULL,'10000000 TL','Sanayi ve Teknoloji Bakanligi',NULL,NULL,NULL,30,NULL,NULL,NULL,1,1,11,NOW(),NOW()),
(12,'Dijital Pazarlama ve E-Ihracat Kapasite Gelistirme','dijital-pazarlama-ve-e-ihracat-kapasite-gelistirme','KOB lere yonelik dijital pazarlama, e-ticaret ve e-ihracat egitim ve danismanlik projesi.','national','ongoing',NULL,NULL,'800000 TL','KOSGEB',NULL,NULL,NULL,70,NULL,NULL,NULL,0,1,12,NOW(),NOW());
