TRUNCATE TABLE legislations;
INSERT INTO legislations (id,title,slug,description,category,date,source,sourceUrl,tags,isImportant,isActive,`order`,createdAt,updatedAt) VALUES
(1,'5174 Sayili Turkiye Odalar ve Borsalar Birligi Kanunu','5174-sayili-turkiye-odalar-ve-borsalar-birligi-kanunu',NULL,'law',NULL,NULL,NULL,NULL,1,1,1,NOW(),NOW()),
(2,'5253 Sayili Dernekler Kanunu','5253-sayili-dernekler-kanunu',NULL,'law',NULL,NULL,NULL,NULL,1,1,2,NOW(),NOW()),
(3,'6102 Sayili Turk Ticaret Kanunu','6102-sayili-turk-ticaret-kanunu',NULL,'law',NULL,NULL,NULL,NULL,1,1,3,NOW(),NOW()),
(4,'4857 Sayili Is Kanunu','4857-sayili-is-kanunu',NULL,'law',NULL,NULL,NULL,NULL,1,1,4,NOW(),NOW()),
(5,'2872 Sayili Cevre Kanunu','2872-sayili-cevre-kanunu',NULL,'law',NULL,NULL,NULL,NULL,0,1,5,NOW(),NOW()),
(6,'6502 Sayili Tuketicinin Korunmasi Hakkinda Kanun','6502-sayili-tuketicinin-korunmasi-hakkinda-kanun',NULL,'law',NULL,NULL,NULL,NULL,0,1,6,NOW(),NOW()),
(7,'5510 Sayili Sosyal Sigortalar ve Genel Saglik Sigortasi Kanunu','5510-sayili-sosyal-sigortalar-ve-genel-saglik-sigortasi-kanunu',NULL,'law',NULL,NULL,NULL,NULL,0,1,7,NOW(),NOW()),
(8,'6331 Sayili Is Sagligi ve Guvenligi Kanunu','6331-sayili-is-sagligi-ve-guvenligi-kanunu',NULL,'law',NULL,NULL,NULL,NULL,1,1,8,NOW(),NOW()),
(9,'Dernekler Yonetmeligi','dernekler-yonetmeligi',NULL,'regulation',NULL,NULL,NULL,NULL,0,1,9,NOW(),NOW()),
(10,'Tekstil Elyaf Isimleri ve Etiketleme Yonetmeligi','tekstil-elyaf-isimleri-ve-etiketleme-yonetmeligi',NULL,'regulation',NULL,NULL,NULL,NULL,1,1,10,NOW(),NOW()),
(11,'CE Isaretlemesi Yonetmeligi','ce-isaretlemesi-yonetmeligi',NULL,'regulation',NULL,NULL,NULL,NULL,1,1,11,NOW(),NOW()),
(12,'Ihracat Rejimi Karari','ihracat-rejimi-karari',NULL,'regulation',NULL,NULL,NULL,NULL,0,1,12,NOW(),NOW()),
(13,'Urun Guvenligi ve Teknik Duzenlemeler Kanunu Uygulama Yonetmeligi','urun-guvenligi-ve-teknik-duzenlemeler-kanunu-uygulama-yonetmeligi',NULL,'regulation',NULL,NULL,NULL,NULL,0,1,13,NOW(),NOW()),
(14,'Gumruk Yonetmeligi Guncel','gumruk-yonetmeligi-guncel',NULL,'regulation',NULL,NULL,NULL,NULL,0,1,14,NOW(),NOW()),
(15,'Kimyasallarin Kaydi Degerlendirilmesi Izni ve Kistlanmasi Hakkinda Yonetmelik KKDK','kimyasallarin-kaydi-degerlendirilmesi-izni-ve-kistlanmasi-hakkinda-yonetmelik-kkdk',NULL,'regulation',NULL,NULL,NULL,NULL,1,1,15,NOW(),NOW()),
(16,'Atik Yonetimi Yonetmeligi','atik-yonetimi-yonetmeligi',NULL,'regulation',NULL,NULL,NULL,NULL,0,1,16,NOW(),NOW()),
(17,'Bazi Tekstil Urunlerinin Ithalatinda Gozetim ve Korunma Onlemleri Yonetmeligi','bazi-tekstil-urunlerinin-ithalatinda-gozetim-ve-korunma-onlemleri-yonetmeligi',NULL,'regulation',NULL,NULL,NULL,NULL,0,1,17,NOW(),NOW()),
(18,'Ihracat Destekleri Hakkinda Karar 2024','ihracat-destekleri-hakkinda-karar-2024',NULL,'circular',NULL,NULL,NULL,NULL,1,1,18,NOW(),NOW()),
(19,'KOSGEB KOB ve Girisimcilik Destekleri Uygulama Esaslari','kosgeb-kob-ve-girisimcilik-destekleri-uygulama-esaslari',NULL,'circular',NULL,NULL,NULL,NULL,1,1,19,NOW(),NOW()),
(20,'Yurt Disi Fuar Katilim Destekleri Genelgesi 2024','yurt-disi-fuar-katilim-destekleri-genelgesi-2024',NULL,'circular',NULL,NULL,NULL,NULL,1,1,20,NOW(),NOW()),
(21,'Turk Urunlerinin Yurt Disinda Markalanmasi TURQUALITY Genelgesi','turk-urunlerinin-yurt-disinda-markalanmasi-turquality-genelgesi',NULL,'circular',NULL,NULL,NULL,NULL,1,1,21,NOW(),NOW()),
(22,'Ar-Ge ve Tasarim Merkezleri Destekleri Uygulama Genelgesi','ar-ge-ve-tasarim-merkezleri-destekleri-uygulama-genelgesi',NULL,'circular',NULL,NULL,NULL,NULL,0,1,22,NOW(),NOW()),
(23,'Yesil Mutabakat Eylem Plani Uygulama Genelgesi','yesil-mutabakat-eylem-plani-uygulama-genelgesi',NULL,'circular',NULL,NULL,NULL,NULL,1,1,23,NOW(),NOW()),
(24,'AB Tekstil Urunleri Yonetmeligi EU 2024-1781','ab-tekstil-urunleri-yonetmeligi-eu-2024-1781',NULL,'international',NULL,NULL,NULL,NULL,1,1,24,NOW(),NOW()),
(25,'REACH Tuz Tekstil Kimyasallar Kistlamalar','reach-tuz-tekstil-kimyasallar-kistlamalar',NULL,'international',NULL,NULL,NULL,NULL,1,1,25,NOW(),NOW()),
(26,'Karbon Sinirda Dzenleme Mekanizmasi CBAM Tuz','karbon-sinirda-dzenleme-mekanizmasi-cbam-tuz',NULL,'international',NULL,NULL,NULL,NULL,1,1,26,NOW(),NOW()),
(27,'AB Dijital Urun Pasaportu Yonetmeligi Taslak','ab-dijital-urun-pasaportu-yonetmeligi-taslak',NULL,'international',NULL,NULL,NULL,NULL,1,1,27,NOW(),NOW()),
(28,'AB Surdurulebilir Urunler icin Eko-Tasarim Yonetmeligi ESPR','ab-surdurulebilir-urunler-icin-eko-tasarim-yonetmeligi-espr',NULL,'international',NULL,NULL,NULL,NULL,1,1,28,NOW(),NOW()),
(29,'ISO 3758 Tekstil Bakim Etiketleme Sembol Standardi','iso-3758-tekstil-bakim-etiketleme-sembol-standardi',NULL,'international',NULL,NULL,NULL,NULL,0,1,29,NOW(),NOW()),
(30,'OEKO-TEX Standart 100 Sertifikasyonu','oeko-tex-standart-100-sertifikasyonu',NULL,'international',NULL,NULL,NULL,NULL,1,1,30,NOW(),NOW()),
(31,'AB Kurumsal Surdurulebilirlik Raporlamasi Direktifi CSRD','ab-kurumsal-surdurulebilirlik-raporlamasi-direktifi-csrd',NULL,'international',NULL,NULL,NULL,NULL,1,1,31,NOW(),NOW()),
(32,'AB Zorla Calistirma Yasagi Tuz','ab-zorla-calistirma-yasagi-tuz',NULL,'international',NULL,NULL,NULL,NULL,1,1,32,NOW(),NOW());
