TRUNCATE TABLE trainings;
INSERT INTO trainings (id,title,slug,description,category,instructor,duration,quota,price,location,eventDate,eventTime,image,syllabus,requirements,isFeatured,isActive,`order`,createdAt,updatedAt) VALUES
(1,'Konfeksiyon Yan Sanayi ve Teknolojileri Egitimi','konfeksiyon-yan-sanayi-ve-teknolojileri-egitimi','Konfeksiyon yan sanayi urunleri, uretim sureleri ve teknolojileri hakkinda detayli egitim programi.','seminar','Dr. Ahmet Yilmaz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,1,NOW(),NOW()),
(2,'Tekstil Kimyasallari ve Surdurulebilirlik','tekstil-kimyasallari-ve-surdurulebilirlik','Tekstil uretiminde kullanilan kimyasallar, cevre standartlari ve surdurulebilir uretim yontemleri.','workshop','Prof. Dr. Elif Demir',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,2,NOW(),NOW()),
(3,'REACH ve AB Kimyasal Yonetmelikleri','reach-ve-ab-kimyasal-yonetmelikleri','AB REACH yonetmeligi, kimyasal guvenlik ve uyum surecleri egitimi.','seminar','Uzm. Mehmet Kaya',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,3,NOW(),NOW()),
(4,'Kalite Yonetim Sistemleri ISO 9001','kalite-yonetim-sistemleri-iso-9001','ISO 9001 kalite yonetim sistemleri, belgelendirme ve uygulamali egitim.','certificate','Belgelendirme Uzmani Ayse Celik',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,4,NOW(),NOW()),
(5,'CE Isaretlemesi ve Urun Guvenligi','ce-isaretlemesi-ve-urun-guvenligi','CE isaretlemesi proseduru, urun guvenlik testleri ve AB piyasasina giris.','seminar','Muhendis Hakan Ozturk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,5,NOW(),NOW()),
(6,'Ihracat Stratejileri ve Dis Pazar Arastirmasi','ihracat-stratejileri-ve-dis-pazar-arastirmasi','Tekstil sektorunde ihracat stratejileri, pazar arastirmasi ve musteri bulma yontemleri.','workshop','Dis Ticaret Uzmani Fatma Yilmaz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,6,NOW(),NOW()),
(7,'Konfeksiyon Yan Sanayi Kalite Yonetimi Semineri','konfeksiyon-yan-sanayi-kalite-yonetimi-semineri','Konfeksiyon yan sanayinde kalite kontrol surecleri, ISO standartlari ve musteri beklentilerinin yonetimi konularinda kapsamli egitim programi.','seminar','Prof. Dr. Ahmet Yilmaz','1 Gun',50,'Ucretsiz','Istanbul Sanayi Odasi Konferans Salonu',NULL,NULL,NULL,NULL,NULL,0,1,7,NOW(),NOW()),
(8,'Surdurulebilir Tekstil Uretimi Workshop','surdurulebilir-tekstil-uretimi-workshop','Cevre dostu uretim teknikleri, geri donusum malzemeleri kullanimi ve karbon ayak izi azaltma stratejileri uzerine uygulamali atolye calismasi.','workshop','Dr. Elif Demir','3 Gun',30,'1500 TL','KYSD Egitim Merkezi',NULL,NULL,NULL,NULL,NULL,0,1,8,NOW(),NOW()),
(9,'Dijital Donusum ve Endustri 4.0 Egitimi','dijital-donusum-ve-endustri-4-0-egitimi','Tekstil ve konfeksiyon sektorunde dijitallasme, akilli fabrika uygulamalari, IoT ve otomasyon sistemleri egitimi.','certificate','Muhendis Mehmet Kaya','15 Gun',100,'2000 TL','Online',NULL,NULL,NULL,NULL,NULL,0,1,9,NOW(),NOW()),
(10,'Fermuar ve Metal Aksesuar Teknik Egitimi','fermuar-ve-metal-aksesuar-teknik-egitimi','Fermuar cesitleri, metal aksesuar uretim teknikleri, kalite testleri ve uluslararasi standartlar hakkinda teknik egitim.','certificate','Uzman Ali Ozkan','3 Gun',40,'1200 TL','Bursa Tekstil OSB',NULL,NULL,NULL,NULL,NULL,0,1,10,NOW(),NOW()),
(11,'Ihracat ve Dis Ticaret Mevzuat Semineri','ihracat-ve-dis-ticaret-mevzuat-semineri','Tekstil ve konfeksiyon sektorune ozel ihracat prosedurleri, gumruk islemleri, tesvikler ve uluslararasi ticaret mevzuati.','seminar','Gumruk Musaviri Fatma Sen','1 Gun',80,'Ucretsiz','ITO Konferans Salonu',NULL,NULL,NULL,NULL,NULL,0,1,11,NOW(),NOW()),
(12,'Etiket Tasarim ve Baski Teknikleri','etiket-tasarim-ve-baski-teknikleri','Modern etiket tasarim trendleri, dijital ve ofset baski teknikleri, RFID etiket uygulamalari uzerine uygulamali egitim.','workshop','Tasarimci Zeynep Arslan','2 Gun',25,'800 TL','KYSD Egitim Merkezi',NULL,NULL,NULL,NULL,NULL,0,1,12,NOW(),NOW()),
(13,'Konfeksiyon Uretiminde Kalite Kontrol Egitimi','konfeksiyon-uretiminde-kalite-kontrol-egitimi','Hazir giyim uretiminde kalite standartlari, olcum teknikleri ve hata tespiti konularinda uygulamali egitim.','seminar','Prof. Dr. Ahmet Yilmaz','2 Gun',30,'Ucretsiz','Istanbul Giyimkent',NULL,NULL,NULL,NULL,NULL,0,1,13,NOW(),NOW()),
(14,'Dijital Pazarlama ve E-Ihracat Stratejileri','dijital-pazarlama-ve-e-ihracat-stratejileri','Tekstil ve konfeksiyon sektorunde dijital pazarlama araclari, e-ticaret platformlari ve B2B satis teknikleri.','workshop','Uzm. Mehmet Ozturk','1 Gun',50,'Ucretsiz','Online',NULL,NULL,NULL,NULL,NULL,0,1,14,NOW(),NOW()),
(15,'Surdurulebilir Uretim ve Sertifikasyon','surdurulebilir-uretim-ve-sertifikasyon','OEKO-TEX, GOTS ve diger cevre sertifikasyonlari hakkinda bilgilendirme ve basvuru surecleri.','seminar','Dr. Zeynep Kaya','1 Gun',40,'Ucretli','Istanbul Ataturk OSB',NULL,NULL,NULL,NULL,NULL,0,1,15,NOW(),NOW()),
(16,'Uretim Planlama ve Stok Yonetimi','uretim-planlama-ve-stok-yonetimi','Konfeksiyon isletmelerinde uretim planlama sistemleri, MRP ve stok optimizasyonu.','seminar','Endustri Muhendisi Ayse Demir','3 Gun',25,'Ucretsiz','Bursa BTSO',NULL,NULL,NULL,NULL,NULL,0,1,16,NOW(),NOW()),
(17,'Ihracat Prosedurleri ve Gumruk Islemleri','ihracat-prosedurleri-ve-gumruk-islemleri','Tekstil ihracatinda gerekli belgeler, gumruk prosedurleri ve mensei ispat.','seminar','Gumruk Musaviri Hasan Celik','1 Gun',35,'Ucretsiz','Izmir EBSO',NULL,NULL,NULL,NULL,NULL,0,1,17,NOW(),NOW());
